'''
##############################################
python train.py --experiment_name nuevo/expe71/WLASL/cris_wholepose_WLASL_lr_0.002 --training_set_path ../../joe/ConnectingPoints/split/WLASL--wholepose-Train.hdf5 --validation_set_path ../../joe/ConnectingPoints/split/WLASL--wholepose-Val.hdf5  --testing_set_path ../../joe/ConnectingPoints/split/WLASL--wholepose-Val.hdf5 --hidden_dim 142 --num_classes 86 --epochs 3 --keypoints_model wholepose --lr 0.002 --keypoints_number 71
python train.py --experiment_name nuevo/expe29/WLASL/cris_wholepose_WLASL_lr_0.002 --training_set_path ../../joe/ConnectingPoints/split/WLASL--wholepose-Train.hdf5 --validation_set_path ../../joe/ConnectingPoints/split/WLASL--wholepose-Val.hdf5  --testing_set_path ../../joe/ConnectingPoints/split/WLASL--wholepose-Val.hdf5 --hidden_dim 58 --num_classes 86 --epochs 3 --keypoints_model wholepose --lr 0.002 --keypoints_number 29

python train.py --experiment_name nuevo/expe71/AEC/cris_mediapipe_AEC_lr_0.001 --training_set_path ../../joe/ConnectingPoints/split/AEC--mediapipe-Train.hdf5 --validation_set_path ../../joe/ConnectingPoints/split/AEC--mediapipe-Val.hdf5  --testing_set_path ../../joe/ConnectingPoints/split/AEC--mediapipe-Val.hdf5 --hidden_dim 142 --num_classes 28 --epochs 3 --keypoints_model mediapipe --lr 0.001 --keypoints_number 71
python train.py --experiment_name nuevo/expe29/AEC/cris_mediapipe_AEC_lr_0.001 --training_set_path ../../joe/ConnectingPoints/split/AEC--mediapipe-Train.hdf5 --validation_set_path ../../joe/ConnectingPoints/split/AEC--mediapipe-Val.hdf5  --testing_set_path ../../joe/ConnectingPoints/split/AEC--mediapipe-Val.hdf5 --hidden_dim 58 --num_classes 28 --epochs 3 --keypoints_model mediapipe --lr 0.001 --keypoints_number 29

python train.py --experiment_name nuevo/expe71/PUCP/cris_wholepose_PUCP_lr_0.0005 --training_set_path ../../joe/ConnectingPoints/split/PUCP_PSL_DGI156--wholepose-Train.hdf5 --validation_set_path ../../joe/ConnectingPoints/split/PUCP_PSL_DGI156--wholepose-Val.hdf5  --testing_set_path ../../joe/ConnectingPoints/split/PUCP_PSL_DGI156--wholepose-Val.hdf5 --hidden_dim 142 --num_classes 29 --epochs 3 --keypoints_model wholepose --lr 0.0005 --keypoints_number 71
python train.py --experiment_name nuevo/expe29/PUCP/cris_wholepose_PUCP_lr_0.0005 --training_set_path ../../joe/ConnectingPoints/split/PUCP_PSL_DGI156--wholepose-Train.hdf5 --validation_set_path ../../joe/ConnectingPoints/split/PUCP_PSL_DGI156--wholepose-Val.hdf5  --testing_set_path ../../joe/ConnectingPoints/split/PUCP_PSL_DGI156--wholepose-Val.hdf5 --hidden_dim 58 --num_classes 29 --epochs 3 --keypoints_model wholepose --lr 0.0005 --keypoints_number 29

python3 train_wandb.py --training_set_path /data/shuaman/psl_gan/Data/landmarks/AEC--wholepose-Train.hdf5 --testing_set_path /data/shuaman/psl_gan/Data/landmarks/AEC--wholepose-Val.hdf5 --validation_set_path /data/shuaman/psl_gan/Data/landmarks/AEC--wholepose-Val.hdf5

'''

############################
python train.py --experiment_name nuevo/final_baneado_71/WLASL/cris_wholepose_WLASL_lr_0.002 --training_set_path ../../joe/ConnectingPoints/split/WLASL--wholepose-Train.hdf5 --validation_set_path ../../joe/ConnectingPoints/split/WLASL--wholepose-Val.hdf5  --testing_set_path ../../joe/ConnectingPoints/split/WLASL--wholepose-Val.hdf5 --hidden_dim 142 --num_classes 86 --epochs 200 --keypoints_model wholepose --lr 0.002 --keypoints_number 71
python train.py --experiment_name nuevo/final_baneado_71/WLASL/cris_mediapipe_WLASL_lr_0.002 --training_set_path ../../joe/ConnectingPoints/split/WLASL--mediapipe-Train.hdf5 --validation_set_path ../../joe/ConnectingPoints/split/WLASL--mediapipe-Val.hdf5  --testing_set_path ../../joe/ConnectingPoints/split/WLASL--mediapipe-Val.hdf5 --hidden_dim 142 --num_classes 86 --epochs 200 --keypoints_model mediapipe --lr 0.002 --keypoints_number 71
python train.py --experiment_name nuevo/final_baneado_71/WLASL/cris_openpose_WLASL_lr_0.002  --training_set_path ../../joe/ConnectingPoints/split/WLASL--openpose-Train.hdf5  --validation_set_path ../../joe/ConnectingPoints/split/WLASL--openpose-Val.hdf5   --testing_set_path ../../joe/ConnectingPoints/split/WLASL--openpose-Val.hdf5  --hidden_dim 142 --num_classes 86 --epochs 200 --keypoints_model openpose  --lr 0.002 --keypoints_number 71

#############################
python train.py --experiment_name nuevo/final_baneado_71/PUCP/cris_wholepose_PUCP_lr_0.0005 --training_set_path ../../joe/ConnectingPoints/split/PUCP_PSL_DGI156--wholepose-Train.hdf5 --validation_set_path ../../joe/ConnectingPoints/split/PUCP_PSL_DGI156--wholepose-Val.hdf5  --testing_set_path ../../joe/ConnectingPoints/split/PUCP_PSL_DGI156--wholepose-Val.hdf5 --hidden_dim 142 --num_classes 29 --epochs 200 --keypoints_model wholepose --lr 0.0005 --keypoints_number 71
python train.py --experiment_name nuevo/final_baneado_71/PUCP/cris_mediapipe_PUCP_lr_0.0005 --training_set_path ../../joe/ConnectingPoints/split/PUCP_PSL_DGI156--mediapipe-Train.hdf5 --validation_set_path ../../joe/ConnectingPoints/split/PUCP_PSL_DGI156--mediapipe-Val.hdf5  --testing_set_path ../../joe/ConnectingPoints/split/PUCP_PSL_DGI156--mediapipe-Val.hdf5 --hidden_dim 142 --num_classes 29 --epochs 200 --keypoints_model mediapipe --lr 0.0005 --keypoints_number 71
python train.py --experiment_name nuevo/final_baneado_71/PUCP/cris_openpose_PUCP_lr_0.0005  --training_set_path ../../joe/ConnectingPoints/split/PUCP_PSL_DGI156--openpose-Train.hdf5  --validation_set_path ../../joe/ConnectingPoints/split/PUCP_PSL_DGI156--openpose-Val.hdf5   --testing_set_path ../../joe/ConnectingPoints/split/PUCP_PSL_DGI156--openpose-Val.hdf5  --hidden_dim 142 --num_classes 29 --epochs 200 --keypoints_model openpose  --lr 0.0005 --keypoints_number 71

############################
python train.py --experiment_name nuevo/final_baneado_71/AEC/cris_wholepose_AEC_lr_0.001 --training_set_path ../../joe/ConnectingPoints/split/AEC--wholepose-Train.hdf5 --validation_set_path ../../joe/ConnectingPoints/split/AEC--wholepose-Val.hdf5  --testing_set_path ../../joe/ConnectingPoints/split/AEC--wholepose-Val.hdf5 --hidden_dim 142 --num_classes 28 --epochs 200 --keypoints_model wholepose --lr 0.001  --keypoints_number 71
python train.py --experiment_name nuevo/final_baneado_71/AEC/cris_mediapipe_AEC_lr_0.001 --training_set_path ../../joe/ConnectingPoints/split/AEC--mediapipe-Train.hdf5 --validation_set_path ../../joe/ConnectingPoints/split/AEC--mediapipe-Val.hdf5  --testing_set_path ../../joe/ConnectingPoints/split/AEC--mediapipe-Val.hdf5 --hidden_dim 142 --num_classes 28 --epochs 200 --keypoints_model mediapipe --lr 0.001  --keypoints_number 71
python train.py --experiment_name nuevo/final_baneado_71/AEC/cris_openpose_AEC_lr_0.001  --training_set_path ../../joe/ConnectingPoints/split/AEC--openpose-Train.hdf5  --validation_set_path ../../joe/ConnectingPoints/split/AEC--openpose-Val.hdf5   --testing_set_path ../../joe/ConnectingPoints/split/AEC--openpose-Val.hdf5  --hidden_dim 142 --num_classes 28 --epochs 200 --keypoints_model openpose  --lr 0.001  --keypoints_number 71

############################

python train.py --experiment_name nuevo/final_baneado_29/WLASL/cris_wholepose_WLASL_lr_0.002 --training_set_path ../../joe/ConnectingPoints/split/WLASL--wholepose-Train.hdf5 --validation_set_path ../../joe/ConnectingPoints/split/WLASL--wholepose-Val.hdf5  --testing_set_path ../../joe/ConnectingPoints/split/WLASL--wholepose-Val.hdf5 --hidden_dim 58 --num_classes 86 --epochs 200 --keypoints_model wholepose --lr 0.002 --keypoints_number 29
python train.py --experiment_name nuevo/final_baneado_29/WLASL/cris_mediapipe_WLASL_lr_0.002 --training_set_path ../../joe/ConnectingPoints/split/WLASL--mediapipe-Train.hdf5 --validation_set_path ../../joe/ConnectingPoints/split/WLASL--mediapipe-Val.hdf5  --testing_set_path ../../joe/ConnectingPoints/split/WLASL--mediapipe-Val.hdf5 --hidden_dim 58 --num_classes 86 --epochs 200 --keypoints_model mediapipe --lr 0.002 --keypoints_number 29
python train.py --experiment_name nuevo/final_baneado_29/WLASL/cris_openpose_WLASL_lr_0.002  --training_set_path ../../joe/ConnectingPoints/split/WLASL--openpose-Train.hdf5  --validation_set_path ../../joe/ConnectingPoints/split/WLASL--openpose-Val.hdf5   --testing_set_path ../../joe/ConnectingPoints/split/WLASL--openpose-Val.hdf5  --hidden_dim 58 --num_classes 86 --epochs 200 --keypoints_model openpose  --lr 0.002 --keypoints_number 29

############################

python train.py --experiment_name nuevo/final_baneado_29/PUCP/cris_wholepose_PUCP_lr_0.0005 --training_set_path ../../joe/ConnectingPoints/split/PUCP_PSL_DGI156--wholepose-Train.hdf5 --validation_set_path ../../joe/ConnectingPoints/split/PUCP_PSL_DGI156--wholepose-Val.hdf5  --testing_set_path ../../joe/ConnectingPoints/split/PUCP_PSL_DGI156--wholepose-Val.hdf5 --hidden_dim 58 --num_classes 29 --epochs 200 --keypoints_model wholepose --lr 0.0005 --keypoints_number 29
python train.py --experiment_name nuevo/final_baneado_29/PUCP/cris_mediapipe_PUCP_lr_0.0005 --training_set_path ../../joe/ConnectingPoints/split/PUCP_PSL_DGI156--mediapipe-Train.hdf5 --validation_set_path ../../joe/ConnectingPoints/split/PUCP_PSL_DGI156--mediapipe-Val.hdf5  --testing_set_path ../../joe/ConnectingPoints/split/PUCP_PSL_DGI156--mediapipe-Val.hdf5 --hidden_dim 58 --num_classes 29 --epochs 200 --keypoints_model mediapipe --lr 0.0005 --keypoints_number 29
python train.py --experiment_name nuevo/final_baneado_29/PUCP/cris_openpose_PUCP_lr_0.0005  --training_set_path ../../joe/ConnectingPoints/split/PUCP_PSL_DGI156--openpose-Train.hdf5  --validation_set_path ../../joe/ConnectingPoints/split/PUCP_PSL_DGI156--openpose-Val.hdf5   --testing_set_path ../../joe/ConnectingPoints/split/PUCP_PSL_DGI156--openpose-Val.hdf5  --hidden_dim 58 --num_classes 29 --epochs 200 --keypoints_model openpose  --lr 0.0005 --keypoints_number 29

############################

python train.py --experiment_name nuevo/final_baneado_29/AEC/cris_wholepose_AEC_lr_0.001 --training_set_path ../../joe/ConnectingPoints/split/AEC--wholepose-Train.hdf5 --validation_set_path ../../joe/ConnectingPoints/split/AEC--wholepose-Val.hdf5  --testing_set_path ../../joe/ConnectingPoints/split/AEC--wholepose-Val.hdf5 --hidden_dim 58 --num_classes 28 --epochs 200 --keypoints_model wholepose --lr 0.001  --keypoints_number 29
python train.py --experiment_name nuevo/final_baneado_29/AEC/cris_mediapipe_AEC_lr_0.001 --training_set_path ../../joe/ConnectingPoints/split/AEC--mediapipe-Train.hdf5 --validation_set_path ../../joe/ConnectingPoints/split/AEC--mediapipe-Val.hdf5  --testing_set_path ../../joe/ConnectingPoints/split/AEC--mediapipe-Val.hdf5 --hidden_dim 58 --num_classes 28 --epochs 200 --keypoints_model mediapipe --lr 0.001  --keypoints_number 29
python train.py --experiment_name nuevo/final_baneado_29/AEC/cris_openpose_AEC_lr_0.001  --training_set_path ../../joe/ConnectingPoints/split/AEC--openpose-Train.hdf5  --validation_set_path ../../joe/ConnectingPoints/split/AEC--openpose-Val.hdf5   --testing_set_path ../../joe/ConnectingPoints/split/AEC--openpose-Val.hdf5  --hidden_dim 58 --num_classes 28 --epochs 200 --keypoints_model openpose  --lr 0.001  --keypoints_number 29
